[window]
padding.x = 5 
padding.y = 5 

[colors.primary]
background = '#0a0008'
foreground = '#fff5fb'

[colors.cursor]
text = '#0a0008'
cursor = '#ff8bd4'

[colors.normal]
black   = '#4b4750'
red     = '#ff6fa6'
green   = '#28d27a'
yellow  = '#ffd166'
blue    = '#7fb3ff'
magenta = '#ff7bd9'
cyan    = '#43e1df'
white   = '#ffffff'

[colors.bright]
black   = '#6e6a73'
red     = '#ff96c9'
green   = '#6af2a1'
yellow  = '#ffe495'
blue    = '#b6dcff'
magenta = '#ff9fe1'
cyan    = '#8ff0ef'
white   = '#ffffff'

